# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHkhapNukougYx5mqS_SiQO3H18vlRA8

# Unemployment Analysis with Python

## Objective
This project analyzes unemployment rate data in India using Python.
The analysis focuses on data cleaning, exploratory data analysis,
visualization, COVID-19 impact, and seasonal trends.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import zipfile
import os

# %matplotlib inline

sns.set_theme(style="whitegrid")

"""Dataset Upload"""

from google.colab import files

uploaded = files.upload()

"""ZIP File Automatically Extract"""

import zipfile
import os

zip_file = list(uploaded.keys())[0]

extract_folder = "unemployment_dataset"

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("Dataset extracted successfully!")
print("Files available:")
print(os.listdir(extract_folder))

"""Dataset Load"""

file_path = os.path.join(
    extract_folder,
    "Unemployment in India.csv"
)

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

df.tail()

df.info()

df.columns = df.columns.str.strip()

print(df.columns.tolist())

print("Missing values in each column:")
print(df.isnull().sum())

df['Date'] = pd.to_datetime(
    df['Date'],
    dayfirst=True,
    errors='coerce'
)

print(df['Date'].head())

df = df.dropna().copy()

print("Shape after removing missing values:", df.shape)

print("Number of duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().copy()

print("Shape after removing duplicates:", df.shape)

df.info()

df.describe()

unemployment_col = 'Estimated Unemployment Rate (%)'

print("Average Unemployment Rate:",
      round(df[unemployment_col].mean(), 2), "%")

print("Minimum Unemployment Rate:",
      round(df[unemployment_col].min(), 2), "%")

print("Maximum Unemployment Rate:",
      round(df[unemployment_col].max(), 2), "%")

df = df.sort_values('Date')

df[['Date', 'Region', unemployment_col]].head(10)

monthly_unemployment = (
    df.groupby('Date')[unemployment_col]
    .mean()
    .reset_index()
)

monthly_unemployment = monthly_unemployment.sort_values('Date')

print(monthly_unemployment)

covid_data = df[df['Date'].dt.year == 2020].copy()

print("2020 data:")
print(covid_data.head())

covid_monthly = (
    covid_data.groupby('Date')[unemployment_col]
    .mean()
    .reset_index()
)

covid_monthly

plt.figure(figsize=(12, 6))

plt.plot(
    covid_monthly['Date'],
    covid_monthly[unemployment_col],
    marker='o'
)

plt.title('Unemployment Rate During COVID-19 Period')
plt.xlabel('Date')
plt.ylabel('Average Unemployment Rate (%)')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

pre_covid = df[df['Date'] < '2020-03-01']

covid_period = df[df['Date'] >= '2020-03-01']

pre_covid_avg = pre_covid[unemployment_col].mean()
covid_avg = covid_period[unemployment_col].mean()

print("Average Unemployment Rate Before COVID-19:",
      round(pre_covid_avg, 2), "%")

print("Average Unemployment Rate During COVID-19 Period:",
      round(covid_avg, 2), "%")

print("Difference:",
      round(covid_avg - pre_covid_avg, 2), "percentage points")

percentage_change = (
    (covid_avg - pre_covid_avg) / pre_covid_avg
) * 100

print(
    "Percentage change in unemployment rate:",
    round(percentage_change, 2),
    "%"
)

area_unemployment = (
    df.groupby('Area')[unemployment_col]
    .mean()
    .reset_index()
)

area_unemployment

plt.figure(figsize=(8, 5))

sns.barplot(
    data=area_unemployment,
    x='Area',
    y=unemployment_col
)

plt.title('Average Unemployment Rate: Rural vs Urban')
plt.xlabel('Area')
plt.ylabel('Average Unemployment Rate (%)')

plt.tight_layout()
plt.show()

region_unemployment = (
    df.groupby('Region')[unemployment_col]
    .mean()
    .sort_values(ascending=False)
)

region_unemployment

"""Top 10 Regions"""

top_10_regions = region_unemployment.head(10)

print("Top 10 regions by average unemployment rate:")
print(top_10_regions)

"""Top 10 Regions Visualization"""

plt.figure(figsize=(12, 6))

top_10_regions.sort_values().plot(kind='barh')

plt.title('Top 10 Regions by Average Unemployment Rate')
plt.xlabel('Average Unemployment Rate (%)')
plt.ylabel('Region')

plt.tight_layout()
plt.show()

"""Bottom 10 Regions"""

bottom_10_regions = region_unemployment.tail(10)

print("10 regions with lower average unemployment rates:")
print(bottom_10_regions)

"""Employment Trend"""

monthly_employment = (
    df.groupby('Date')['Estimated Employed']
    .mean()
    .reset_index()
)

plt.figure(figsize=(12, 6))

plt.plot(
    monthly_employment['Date'],
    monthly_employment['Estimated Employed'],
    marker='o'
)

plt.title('Average Estimated Employment Trend')
plt.xlabel('Date')
plt.ylabel('Estimated Employed')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""Labour Participation Rate"""

monthly_lpr = (
    df.groupby('Date')['Estimated Labour Participation Rate (%)']
    .mean()
    .reset_index()
)

plt.figure(figsize=(12, 6))

plt.plot(
    monthly_lpr['Date'],
    monthly_lpr['Estimated Labour Participation Rate (%)'],
    marker='o'
)

plt.title('Labour Participation Rate Trend')
plt.xlabel('Date')
plt.ylabel('Labour Participation Rate (%)')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""Seasonal Trend Analysis"""

df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.strftime('%B')

monthly_pattern = (
    df.groupby(['Month', 'Month_Name'])[unemployment_col]
    .mean()
    .reset_index()
    .sort_values('Month')
)

monthly_pattern

"""Monthly Seasonal Pattern Graph

"""

plt.figure(figsize=(12, 6))

sns.lineplot(
    data=monthly_pattern,
    x='Month_Name',
    y=unemployment_col,
    marker='o'
)

plt.title('Monthly Pattern of Unemployment Rate')
plt.xlabel('Month')
plt.ylabel('Average Unemployment Rate (%)')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""Highest Unemployment Observation"""

highest_unemployment = df.loc[
    df[unemployment_col].idxmax()
]

print("Highest unemployment observation:")
print(highest_unemployment)

"""Lowest Unemployment Observation"""

lowest_unemployment = df.loc[
    df[unemployment_col].idxmin()
]

print("Lowest unemployment observation:")
print(lowest_unemployment)

"""Correlation Analysis"""

correlation = df[
    [
        unemployment_col,
        'Estimated Employed',
        'Estimated Labour Participation Rate (%)'
    ]
].corr()

correlation

"""Correlation Heatmap"""

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Between Employment Indicators')

plt.tight_layout()
plt.show()

"""Final Summary Automatically Generate"""

print("========== UNEMPLOYMENT ANALYSIS SUMMARY ==========")

print(
    "Overall Average Unemployment Rate:",
    round(df[unemployment_col].mean(), 2),
    "%"
)

print(
    "Highest Unemployment Rate:",
    round(df[unemployment_col].max(), 2),
    "%"
)

print(
    "Lowest Unemployment Rate:",
    round(df[unemployment_col].min(), 2),
    "%"
)

print(
    "Pre-COVID Average:",
    round(pre_covid_avg, 2),
    "%"
)

print(
    "COVID Period Average:",
    round(covid_avg, 2),
    "%"
)

print(
    "Change During COVID Period:",
    round(covid_avg - pre_covid_avg, 2),
    "percentage points"
)

print(
    "Highest Average Region:",
    region_unemployment.index[0]
)

print(
    "Lowest Average Region:",
    region_unemployment.index[-1]
)

"""Clean Final Dataset Save"""

cleaned_file = "cleaned_unemployment_data.csv"

df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved successfully!")

from google.colab import files

files.download(cleaned_file)